version: '3'
services:
  nginx:
    image: nginx
    ports: 
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html
  mysql:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
